GET http://localhost:8080/api/v1
//To get server status
###
GET http://localhost:8080/api/v1/jobs

###
GET http://localhost:8080/api/v1/jobs/6517d09f9613bd2548525740

###
###
GET http://localhost:8080/api/v1/jobs/6517d407ef787dd47c100551

###
POST http://localhost:8080/api/v1/jobs
Content-Type: application/json

{
      "user_email" : "oloogeorge633@gmail.com",
      "title" : "Test Web Dev",
      "Services" : "Web Development",
      "description":"A detailed description",
      "skills" : "NodeJs, ExpressJs, NextJs",
      "budget": 1200,
      "duration" : 4
}

###