GET http://localhost:8080/api/v1
//To get server status
###
GET https://assist-api-okgk.onrender.com/api/v1
//To get server status
###
GET http://localhost:8080/api/v1/jobs

###
GET http://localhost:8080/api/v1/download/6513d0c7761b2becc9447951/6513d0c7761b2becc9447952

###

job id..................6513d0c7761b2becc9447951
file id....................... 6513d0c7761b2becc9447952
title: Topic 7 DQ1.edited.docx
###
GET http://localhost:8080/api/v1/profile/64fee35c195c98e3040f0746

###
GET http://localhost:8080/api/v1/profile/64fee35c195c98e3040f0746

###
PATCH http://localhost:8080/api/v1/profile/64fee35c195c98e3040f0746
Content-Type: application/json

{
"tasks": ["Web Development", "App Development"],
"skills": ["HTML/CSS", "ReactJS", "NodeJs", "Tailwind CSS", "React Native"],
"location": "Langas",
"rating": 4.6,
"bio": "About me, the new user"
}

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "oloogeorge633@gmail.com",
    "password": "Olosko2018?"
}

###
POST http://localhost:8080/api/v1/register/client
Content-Type: application/json

{
    "name": "Olosko",
    "type": "Inidividual Client",
    "email": "oloogeorge633@gmail.com",
    "password": "Olosko2018?"
}

###
POST http://localhost:8080/api/v1/register/freelancer
Content-Type: application/json

{
    "name": "Collo21",
    "type": "Beginner VA",
    "email": "collog@gmail.com",
    "password": "Olosko2018?"
}


###
POST http://localhost:8080/api/v1/reset 
Content-Type: application/json

{
    "email": "collog1824@gmail.com"
}

###
//Send Bot messages
POST http://localhost:8080/api/v1/bot/message
Content-Type: application/json

{
    "message": "How can I reset my password?"
}
###
//Send Bot messages
POST http://localhost:8080/api/v1/bot/message
Content-Type: application/json

{
    "message": "How do I contact customer support?"
}
###
//Send Bot messages
POST http://localhost:8080/api/v1/bot/message
Content-Type: application/json

{
    "message": "hello"
}
###
###
//Send Bot messages
POST http://localhost:8080/api/v1/bot/message
Content-Type: application/json

{
    "message": "how can I find a virtual assistant in your platform?"
}
###
//Send Bot messages
POST http://localhost:8080/api/v1/bot/message
Content-Type: application/json

{
    "message": "how do you make payments?"
}
###
ws http://localhost:8080/api/v1/chat
Content-Type: application/json

{
    "message": "hello"
}
###
POST http://localhost:8080/api/v1/bid
Content-Type: application/json

{
    "message": "hello"
}