GET http://localhost:8080/api/v1
//To get server status
###
GET http://localhost:8080/api/v1/all/users

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email": "collo@gmail.com",
    "password": "Olosko2018?"
}

###
POST http://localhost:8080/api/v1/register/client
Content-Type: application/json

{
    "name": "Collog",
    "type": "Business Client",
    "email": "collog1824@gmail.com",
    "password": "Olosko2018?"
}

###
POST http://localhost:8080/api/v1/register/freelancer
Content-Type: application/json

{
    "name": "Collo",
    "type": "Experienced VA",
    "email": "collo@gmail.com",
    "password": "Olosko2018?"
}


###
POST http://localhost:8080/api/v1/reset 
Content-Type: application/json

{
    "email": "collog1824@gmail.com"
}